package ouraapi

import (
	"context"
	"encoding/json"
	"net/url"

	"github.com/ouracli/oura/internal/envelope"
)

// The endpoint registry is the single source of truth for ouracli. The cobra
// data commands, the MCP tool list, and the `oura schema` manifest are all
// generated by iterating Endpoints, so the three surfaces cannot drift.

// Style classifies an endpoint's query-parameter shape and response envelope.
type Style int

const (
	// StyleDateRange: start_date/end_date (YYYY-MM-DD) + next_token, and
	// usually a fields projection; response is {"data":[...],"next_token"}.
	StyleDateRange Style = iota
	// StyleDatetimeRange: start_datetime/end_datetime (RFC3339) + latest +
	// next_token; time-series data with no per-document routes.
	StyleDatetimeRange
	// StyleTokenOnly: next_token + fields only, no date window
	// (ring_configuration).
	StyleTokenOnly
	// StyleSingleObject: no query params, and a bare JSON object response
	// rather than a data/next_token envelope (personal_info).
	StyleSingleObject
)

// Endpoint describes one Oura v2 usercollection resource.
type Endpoint struct {
	CLI        string // CLI command name, e.g. "sleep"
	MCPTool    string // MCP tool name, e.g. "oura_sleep"
	Path       string // API path, e.g. "/usercollection/daily_sleep"
	Short      string // one-line description of what the data is
	Style      Style
	HasDocID   bool // GET .../{document_id} exists
	HasFields  bool // supports the fields query param
	Sandbox    bool // available under /v2/sandbox
	Deprecated bool
}

// Endpoints is every v2 usercollection endpoint ouracli exposes. Order here is
// the order commands appear in the CLI and the schema manifest.
var Endpoints = []Endpoint{
	{
		CLI: "sleep", MCPTool: "oura_sleep", Path: "/usercollection/daily_sleep",
		Short: "Daily sleep score (0-100) with contributor breakdown: deep sleep, REM, latency, efficiency, restfulness, and timing.",
		Style: StyleDateRange, HasDocID: true, HasFields: true, Sandbox: true,
	},
	{
		CLI: "sleep-periods", MCPTool: "oura_sleep_periods", Path: "/usercollection/sleep",
		Short: "Detailed per-period sleep sessions: bedtime, sleep phases (deep/REM/light/awake), heart rate, HRV, breathing, efficiency, and latency.",
		Style: StyleDateRange, HasDocID: true, HasFields: true, Sandbox: true,
	},
	{
		CLI: "sleep-time", MCPTool: "oura_sleep_time", Path: "/usercollection/sleep_time",
		Short: "Recommended optimal bedtime window and sleep-timing status/recommendation for a given day.",
		Style: StyleDateRange, HasDocID: true, HasFields: true, Sandbox: true,
	},
	{
		CLI: "activity", MCPTool: "oura_activity", Path: "/usercollection/daily_activity",
		Short: "Daily activity score with steps, active/total calories, MET minutes, and time spent in each intensity zone.",
		Style: StyleDateRange, HasDocID: true, HasFields: true, Sandbox: true,
	},
	{
		CLI: "readiness", MCPTool: "oura_readiness", Path: "/usercollection/daily_readiness",
		Short: "Daily readiness score with contributors (resting heart rate, HRV balance, recovery index, body temperature) and temperature deviation.",
		Style: StyleDateRange, HasDocID: true, HasFields: true, Sandbox: true,
	},
	{
		CLI: "stress", MCPTool: "oura_stress", Path: "/usercollection/daily_stress",
		Short: "Daily stress summary: high-stress and recovery-time totals (seconds) plus an overall day-summary label.",
		Style: StyleDateRange, HasDocID: true, HasFields: true, Sandbox: true,
	},
	{
		CLI: "resilience", MCPTool: "oura_resilience", Path: "/usercollection/daily_resilience",
		Short: "Long-term resilience level with contributors: sleep recovery, daytime recovery, and stress.",
		Style: StyleDateRange, HasDocID: true, HasFields: false, Sandbox: true,
	},
	{
		CLI: "spo2", MCPTool: "oura_spo2", Path: "/usercollection/daily_spo2",
		Short: "Daily average blood-oxygen (SpO2) percentage during sleep and the breathing-disturbance index.",
		Style: StyleDateRange, HasDocID: true, HasFields: true, Sandbox: true,
	},
	{
		CLI: "cardio-age", MCPTool: "oura_cardio_age", Path: "/usercollection/daily_cardiovascular_age",
		Short: "Estimated vascular age and pulse-wave velocity from cardiovascular-age analysis.",
		Style: StyleDateRange, HasDocID: true, HasFields: true, Sandbox: true,
	},
	{
		CLI: "vo2max", MCPTool: "oura_vo2max", Path: "/usercollection/vO2_max",
		Short: "Estimated VO2 max (cardiorespiratory fitness) with the day it was calculated.",
		Style: StyleDateRange, HasDocID: true, HasFields: true, Sandbox: true,
	},
	{
		CLI: "heartrate", MCPTool: "oura_heartrate", Path: "/usercollection/heartrate",
		Short: "Time-series heart-rate (bpm) samples tagged by source (awake/rest/sleep/workout); queried over an RFC3339 datetime range.",
		Style: StyleDatetimeRange, HasDocID: false, HasFields: false, Sandbox: true,
	},
	{
		CLI: "battery", MCPTool: "oura_battery", Path: "/usercollection/ring_battery_level",
		Short: "Time-series ring battery level (%) with charging state; queried over an RFC3339 datetime range.",
		Style: StyleDatetimeRange, HasDocID: false, HasFields: false, Sandbox: true,
	},
	{
		CLI: "workouts", MCPTool: "oura_workouts", Path: "/usercollection/workout",
		Short: "Logged workouts: activity type, intensity, calories, distance, source, and start/end times.",
		Style: StyleDateRange, HasDocID: true, HasFields: true, Sandbox: true,
	},
	{
		CLI: "sessions", MCPTool: "oura_sessions", Path: "/usercollection/session",
		Short: "Guided or logged sessions (meditation, breathing, etc.): type, mood, heart rate, HRV, and motion during the session.",
		Style: StyleDateRange, HasDocID: true, HasFields: true, Sandbox: true,
	},
	{
		CLI: "tags", MCPTool: "oura_tags", Path: "/usercollection/enhanced_tag",
		Short: "Enhanced tags: user-annotated events with tag type, custom name, comment, and start/end times.",
		Style: StyleDateRange, HasDocID: true, HasFields: true, Sandbox: true,
	},
	{
		CLI: "tags-legacy", MCPTool: "oura_tags_legacy", Path: "/usercollection/tag",
		Short: "Legacy tags (deprecated): freeform text notes with a timestamp and tag list. Prefer 'tags' (enhanced_tag).",
		Style: StyleDateRange, HasDocID: true, HasFields: true, Sandbox: true, Deprecated: true,
	},
	{
		CLI: "rest-mode", MCPTool: "oura_rest_mode", Path: "/usercollection/rest_mode_period",
		Short: "Rest Mode periods: start/end days and per-episode detail while the ring was in recovery/rest mode.",
		Style: StyleDateRange, HasDocID: true, HasFields: true, Sandbox: true,
	},
	{
		CLI: "ring", MCPTool: "oura_ring", Path: "/usercollection/ring_configuration",
		Short: "Ring hardware configuration: color, design, hardware type, size, firmware version, and setup date.",
		Style: StyleTokenOnly, HasDocID: true, HasFields: true, Sandbox: true,
	},
	{
		CLI: "profile", MCPTool: "oura_profile", Path: "/usercollection/personal_info",
		Short: "Personal info: user id, age, biological sex, height, weight, and email.",
		Style: StyleSingleObject, HasDocID: false, HasFields: false, Sandbox: false,
	},
}

// FindEndpoint returns the endpoint registered under the given CLI name.
func FindEndpoint(cli string) (Endpoint, bool) {
	for _, ep := range Endpoints {
		if ep.CLI == cli {
			return ep, true
		}
	}
	return Endpoint{}, false
}

// List fetches one page of ep's collection with the caller-built query (start
// date, next_token, fields, etc.) and returns the {"data",...,"next_token"}
// envelope. The caller owns the query so it can honor ep.Style.
func (c *Client) List(ctx context.Context, ep Endpoint, q url.Values) (*ListResponse, error) {
	if ep.Style == StyleSingleObject {
		return nil, envelope.New(envelope.KindUsage, "not_listable",
			ep.CLI+" returns a single object, not a collection",
			"call the endpoint without --start/--end/--all")
	}
	var lr ListResponse
	if err := c.Get(ctx, ep.Path, q, &lr); err != nil {
		return nil, err
	}
	return &lr, nil
}

// Doc fetches a single document by id from ep's collection. When ep supports
// the fields projection and fields is non-empty, it is passed through.
func (c *Client) Doc(ctx context.Context, ep Endpoint, id, fields string) (json.RawMessage, error) {
	if !ep.HasDocID {
		return nil, envelope.New(envelope.KindUsage, "no_document_route",
			ep.CLI+" has no per-document endpoint",
			"fetch the collection instead and filter client-side")
	}
	q := url.Values{}
	if ep.HasFields && fields != "" {
		q.Set("fields", fields)
	}
	var raw json.RawMessage
	if err := c.Get(ctx, ep.Path+"/"+id, q, &raw); err != nil {
		return nil, err
	}
	return raw, nil
}

// Object fetches ep's bare single-object response (personal_info), returned as
// raw JSON.
func (c *Client) Object(ctx context.Context, ep Endpoint) (json.RawMessage, error) {
	if ep.Style != StyleSingleObject {
		return nil, envelope.New(envelope.KindUsage, "not_single_object",
			ep.CLI+" returns a collection, not a single object",
			"use the list form with --start/--end")
	}
	var raw json.RawMessage
	if err := c.Get(ctx, ep.Path, nil, &raw); err != nil {
		return nil, err
	}
	return raw, nil
}

// ListAll follows next_token pagination from the caller-built starting query,
// invoking emit once per document across every page until next_token is null.
// A non-nil error from emit stops the walk and is returned.
func (c *Client) ListAll(ctx context.Context, ep Endpoint, q url.Values, emit func(json.RawMessage) error) error {
	// Copy so we can mutate next_token without clobbering the caller's values.
	page := url.Values{}
	for k, vs := range q {
		page[k] = append([]string(nil), vs...)
	}
	for {
		lr, err := c.List(ctx, ep, page)
		if err != nil {
			return err
		}
		for _, doc := range lr.Data {
			if err := emit(doc); err != nil {
				return err
			}
		}
		if lr.NextToken == nil || *lr.NextToken == "" {
			return nil
		}
		page.Set("next_token", *lr.NextToken)
	}
}
